import Head from 'next/head';
import Item from '../components/item';
import Link from 'next/link';

export default function Home({movies,series}) {
  return (
    <>
      <Head>
        <title>Watchfilx</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="SectionTitle">New Movies</div>
      <div className='container' id='movies'>
        {movies.map((item)=> {
          return <Item key={item[0]} id={item[0]} title={item[1]} film={"movie"} />
        })}

      </div>
      <Link href="/movies"><a className="ViewMore">View More</a></Link>
      <div className="SectionTitle">New Series Episodes</div>
      <div className='container' id='series'>
        {series.map((item)=> {
          return <Item key={item[0]}  id={item[0]} title={item[1]} film={"serie"} />
        })}
      </div>
      <Link href="/series"><a className="ViewMore">View More</a></Link>
    </>
  )
}

export async function getServerSideProps(context) {
  const res = await Promise.all( [fetch('https://backend-watchflix.herokuapp.com/api/newMovies?page=1&limit=18'), fetch('https://backend-watchflix.herokuapp.com/api/newSeries?page=1&limit=18')]);
  const json = await Promise.all( [res[0].json(), res[1].json()] );
  return {
    props: {
        movies: json[0],
        series: json[1]
    }, // will be passed to the page component as props
  }
}